apiVersion: v1
kind: Service
metadata:
  labels:
    app: lunar-system
  name: lunar-system-service
spec:
  ports:
  - port: 80 #change to 80
    protocol: TCP
    targetPort: 80
  selector:
    app: lunar-system
  type: LoadBalancer